name: Deploy to Firebase Hosting on merge
"on":
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Change directory to frontend
        run: cd frontend

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "21" # このバージョン指定は見直す必要があります

      - name: Install Dependencies
        run: npm install

      - name: Build and Export Next.js app
        run: |
          npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SOCRATES_413218 }}"
          channelId: live
          projectId: socrates-413218
